[build]
  command = "npm run build"
  publish = "out"

[[redirects]]
  from = "/static/pricing.html"
  to = "/static/pricing.html"
  status = 200

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
